// PLAYER ACTIONS
export const UPDATE_PLAYER_MONITOR = 'UPDATE_PLAYER';
export const UPDATE_PLAYER_CLOCK = 'UPDATE_PLAYER_CLOCK';
export const UPDATE_PLAYER_SOURCE = 'UPDATE_PLAYER_SOURCE';
export const UPDATE_PLAYER_ISPLAYING = 'UPDATE_PLAYER_ISPLAYING';
export const UPDATE_PLAYER_PLAYRATE = 'UPDATE_PLAYER_PLAYRATE';
export const UPDATE_PLAYER_JOGSTEP = 'UPDATE_PLAYER_JOGSTEP';

// RECORDER ACTIONS
export const UPDATE_RECORDER_MONITOR = 'UPDATE_RECORDER';
export const UPDATE_RECORDER_CLOCK = 'UPDATE_RECORDER_CLOCK';
