// PLAYER ACTIONS
export const UPDATE_PLAYER_MONITOR = 'UPDATE_PLAYER';
export const UPDATE_PLAYER_CLOCK = 'UPDATE_PLAYER_CLOCK';
export const UPDATE_PLAYER_SOURCE = 'UPDATE_PLAYER_SOURCE';
export const UPDATE_PLAYER_STREAM = 'UPDATE_PLAYER_STREAM';
export const UPDATE_PLAYER_ISPLAYING = 'UPDATE_PLAYER_ISPLAYING';
export const UPDATE_PLAYER_PLAYRATE = 'UPDATE_PLAYER_PLAYRATE';
export const UPDATE_PLAYER_JOGSTEP = 'UPDATE_PLAYER_JOGSTEP';

// RECORDER ACTIONS
export const UPDATE_RECORDER_MONITOR = 'UPDATE_RECORDER';
export const UPDATE_RECORDER_CLOCK = 'UPDATE_RECORDER_CLOCK';
export const ADD_RECORDER_SOURCE = 'ADD_RECORDER_SOURCE';
export const UPDATE_RECORDER_SOURCE = 'UPDATE_RECORDER_SOURCE';
export const UPDATE_RECORDER_ISLOADED = 'UPDATE_RECORDER_ISLOADED';
export const UPDATE_RECORDER_ISPLAYING = 'UPDATE_RECORDER_ISPLAYING';
export const UPDATE_RECORDER_PLAYRATE = 'UPDATE_RECORDER_PLAYRATE';
export const UPDATE_RECORDER_JOGSTEP = 'UPDATE_RECORDER_JOGSTEP';
export const UPDATE_PREVIEW_CLIP = 'UPDATE_PREVIEW_CLIP';
export const UPDATE_CLIPSJSON = 'UPDATE_CLIPSJSON';


// OTHER ACTIONS
export const UPDATE_USER = 'UPDATE_USER';
